webtalk_init -webtalk_dir /home/alik/repos/DDCA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/FSM_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 12 19:47:27 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2d2c15ca-28c1-4e74-bcbe-c4c0b7fd993b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6d203bcddf68407095fa30a880543690" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "131" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "EndeavourOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "EndeavourOS Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3739.627 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "481 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114612_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1746157546 -regid "" -xml /home/alik/repos/DDCA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/FSM_test_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/alik/repos/DDCA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/FSM_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/alik/repos/DDCA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/FSM_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
