# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nimbes/ddca/dimmedLed/dimmedLed.cache/wt [current_project]
set_property parent.project_path /home/nimbes/ddca/dimmedLed/dimmedLed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo /home/nimbes/ddca/dimmedLed/dimmedLed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/sources_1/new/4-16Decoder.v
  /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/sources_1/imports/new/clk_div.v
  /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/sources_1/new/ledNextStateLogic.v
  /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/sources_1/new/ledStateRegister.v
  /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/sources_1/new/dimmedLed.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/constrs_1/imports/constr/basys3Constraints.xdc
set_property used_in_implementation false [get_files /home/nimbes/ddca/dimmedLed/dimmedLed.srcs/constrs_1/imports/constr/basys3Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dimmedLed -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dimmedLed.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dimmedLed_utilization_synth.rpt -pb dimmedLed_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
