#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 12 19:46:01 CEST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim FSM_test_behav -key {Behavioral:sim_1:Functional:FSM_test} -tclbatch FSM_test.tcl -log simulate.log"
xsim FSM_test_behav -key {Behavioral:sim_1:Functional:FSM_test} -tclbatch FSM_test.tcl -log simulate.log

